apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-sa
  namespace: cattle-ai-agent-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-role
  namespace: cattle-ai-agent-system
rules:
{{- if not .Values.insecureSkipTls }}
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["cattle-mcp-ca"]
{{- end }}
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "update", "patch"]
  resourceNames: ["rancher-ai-agent"]
- apiGroups: ["ai.cattle.io"]
  resources: ["aiagentconfigs"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-agent-sa
  namespace: cattle-ai-agent-system
subjects:
- kind: ServiceAccount
  name: agent-sa
  namespace: cattle-ai-agent-system
roleRef:
  kind: Role
  name: agent-role
  apiGroup: rbac.authorization.k8s.io
