aiAgent:
  image:
    repository: ghcr.io/rancher-sandbox/rancher-ai-agent
    tag: v0.1.2-alpha.1
    pullPolicy: IfNotPresent
mcp:
  image:
    repository: ghcr.io/rancher-sandbox/rancher-ai-mcp
    tag: v0.1.1
    pullPolicy: IfNotPresent

llmModel: ""
ollamaLlmModel: ""
geminiLlmModel: ""
openaiLlmModel: ""
bedrockLlmModel: ""
ollamaUrl: ""
googleApiKey:
openaiApiKey:
openaiUrl:
awsBedrock:
  bearerToken:
  accessKeyId:
  secretAccessKey:
  region:
activeLlm: # ollama, gemini, openai, bedrock
# Enable RAG with embedded rancher documentation
rag:
    enabled: false
    embeddings_model:
    pvc:
langfuseSecretKey:
langfusePublicKey:
langfuseHost:
storage:
  enabled: false
  connectionString: ""
insecureSkipTls: false
llmMock:
  enabled: false
  url: ""
log:
  level: info
